Repository JuliaFolds2/OhMyThreads.jl, pull requests merged in 2024-09, with the labels that each got.

#117 Support for `enumerate(chunks(...))`
  CHANGELOG.md
  src/implementation.jl
  test/runtests.jl
Labels: enhancement

#126 Clarify the scope of `@set` and `@local`
  src/macros.jl
Labels: Skip-Changelog

#127 DocumenterInterLinks
  docs/Project.toml
  docs/make.jl
  docs/src/refs/api.md
Labels: documentation, Skip-Changelog

#121 Add concurrency safe iterator wrapper ChannelLike
  CHANGELOG.md
  docs/src/literate/tls/tls.jl
  docs/src/literate/tls/tls.md
  docs/src/refs/api.md
  src/implementation.jl
  src/schedulers.jl
  src/types.jl
Labels: enhancement, new feature, needs changelog
