Repository JuliaFolds2/OhMyThreads.jl, pull requests merged in 2024-02, with the labels that each got.

#19 Correct doc string for `treduce`
  src/OhMyThreads.jl
Labels: docfix

#29 Base.Threads → OhMyThreads translation page for docs
  docs/make.jl
  docs/src/refs/api.md
  docs/src/translation.md
Labels: documentation

#44 Add GH action to enforce CHANGELOG.md updates for PRs
  .github/workflows/changelog.yml
Labels: Skip-Changelog

#45 Schedulers as `struct`s
  CHANGELOG.md
  README.md
  docs/make.jl
  docs/src/examples/integration/integration.jl
  docs/src/examples/integration/integration.md
  docs/src/examples/juliaset/juliaset.jl
  docs/src/examples/juliaset/juliaset.md
  docs/src/examples/mc/mc.jl
  docs/src/examples/mc/mc.md
  docs/src/examples/tls/tls.jl
  docs/src/examples/tls/tls.md
  docs/src/examples/tomarkdown.sh
  docs/src/index.md
  docs/src/refs/api.md
  docs/src/translation.md
  src/OhMyThreads.jl
  src/implementation.jl
  src/schedulers.jl
  test/runtests.jl
Labels: breaking

#46 `SpawnAllScheduler`
  CHANGELOG.md
  docs/src/refs/api.md
  docs/src/translation.md
  src/OhMyThreads.jl
  src/implementation.jl
  src/schedulers.jl
  test/runtests.jl
Labels: new feature

#48 Basic support for `ChunkSplitters.Chunk` + `nchunks=0`
  CHANGELOG.md
  Project.toml
  docs/src/refs/api.md
  docs/src/translation.md
  src/OhMyThreads.jl
  src/implementation.jl
  src/schedulers.jl
  test/runtests.jl
Labels: new feature, needs docs, deprecation

#55 Remove stale imports etc
  src/OhMyThreads.jl
  src/implementation.jl
  src/schedulers.jl
Labels: Skip-Changelog

#58 Improve docs
  CHANGELOG.md
  README.md
  docs/make.jl
  docs/src/basics.md
  docs/src/examples/tls/tls.jl
  docs/src/examples/tls/tls.md
  docs/src/literate/Project.toml
  docs/src/literate/integration/Project.toml
  docs/src/literate/integration/integration.jl
  docs/src/literate/integration/integration.md
  docs/src/literate/juliaset/Project.toml
  docs/src/literate/juliaset/juliaset-10.png
  docs/src/literate/juliaset/juliaset-8.png
  docs/src/literate/juliaset/juliaset.jl
  docs/src/literate/juliaset/juliaset.md
  docs/src/literate/mc/Project.toml
  docs/src/literate/mc/mc.jl
  docs/src/literate/mc/mc.md
  docs/src/literate/tls/Project.toml
  docs/src/literate/tls/tls.jl
  docs/src/literate/tls/tls.md
  docs/src/literate/tomarkdown.sh
  docs/src/translation.md
Labels: documentation, Skip-Changelog
